# Generated by Django 5.0.4 on 2024-04-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id'], 'verbose_name': 'author', 'verbose_name_plural': 'the author'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id'], 'verbose_name': 'a tool', 'verbose_name_plural': 'tools'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'service', 'verbose_name_plural': 'types of service'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['id'], 'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ['-id'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-id'], 'verbose_name': 'work', 'verbose_name_plural': 'works'},
        ),
        migrations.RemoveField(
            model_name='work',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='work',
            name='stack',
        ),
    ]
